Moved ReloadResponse to facilities-api and updated tests for coverage.
department-of-veterans-affairs/lighthouse-facilities pull request #188
Opened 2021-01-14 15:44 UTC by taylorrassmannlibertyits

2021-01-14 19:18 UTC, jnguy-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  // See ReloadIT.java or InternalFacilitiesControllerTest.java for more
Does this not work if you put it inside of `InternalFacilitiesControllerTest.java`?

2021-01-14 19:20 UTC, jnguy-va submitted a review, later dismissed
Quick blanket tests passed, deferring to @as-va  for final approval.

2021-01-14 19:26 UTC, taylorrassmannlibertyits commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  // See ReloadIT.java or InternalFacilitiesControllerTest.java for more
Unfortunately no. There are calls to that area of code in the `InternalFacilitiesControllerTest` already and the coverage wasn't picked up. I tested your suggestion to make sure too and nope :'(

2021-01-14 21:34 UTC, as-va requested changes

2021-01-14 21:34 UTC, as-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  // See ReloadIT.java or InternalFacilitiesControllerTest.java for more
The coverage isn't picked up in the other module because only the module being tested gets instrumented and code coverage can only be captured from the instrumented version of the file, therefore you can't (*) have a test in one module generate code coverage on a source file in a different module.

(*) Well, you _can_ configure maven/jacoco to do this, but I don't thinks that's the direction we should go.

2021-01-14 21:34 UTC, as-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  void reloadCoverageTest() {
This is not a real test. The file path, file name, class name, function annotation, and function name all say it is, but they are all lying.

`InternalFacilitiesControllerTest` may be covering some of this (`ReloadResponse`) class by nature of using it, but this class is now owned by the `facilities-api` module, and each module is responsible for testing the code within it. I think we should have a real set of tests here.

2021-01-14 22:50 UTC, taylorrassmannlibertyits commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  // See ReloadIT.java or InternalFacilitiesControllerTest.java for more
This creates a large dependency change to the entire project to fully test ReloadResponse in this new module. Is your decision for me to spend time and effort to migrate this over since it is already completed in the other module?

2021-01-14 23:18 UTC, as-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  // See ReloadIT.java or InternalFacilitiesControllerTest.java for more
Lets talk offline about scope and LOE concerns.

2021-01-14 23:25 UTC, jblefkove-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  void reloadCoverageTest() {
It should be straightforward to turn these into real tests, no? i.e. add an assertion to check that `markComplete()` set the expected timestamp?

2021-01-15 13:22 UTC, taylorrassmannlibertyits commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/v0/ReloadResponseTest.java
> +  void reloadCoverageTest() {
I was overcomplicating the issue. Will make a simple test for this. Thanks all.

2021-01-15 15:29 UTC, as-va approved these changes

2021-01-15 15:30 UTC, merged