Initial update for version one upgrade
department-of-veterans-affairs/lighthouse-facilities pull request #227
Opened 2021-07-01 13:34 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-8058
and
https://vajira.max.gov/browse/API-8059

Big update implementing v1 initial classes for upgrade. There is A LOT of duplication here, however, this is intentional. As the team progresses forward with v1 changes for Facilities, the v1 code will diverge from v0.

2021-07-01 14:57 UTC, as-va commented
Looks like this is moving forward with bifurcating at the db level with the versioned Facility strings. Did you look into the unversioned Facility db representation and translating after reading like we had discussed last week? Did you identify any problems with the other approach or just think that this is better?

2021-07-01 15:10 UTC, taylorrassmannlibertyits commented
> Looks like this is moving forward with bifurcating at the db level with the versioned Facility strings. Did you look into the unversioned Facility db representation and translating after reading like we had discussed last week? Did you identify any problems with the other approach or just think that this is better?

Saving to the db has to be _some version_ and that would be represented as v0 (at the moment). I thought about it a bit more, and saw the implemented path forward as the way to go. I think a daily save of two different facility types is better than having to transform for each call.

2021-07-01 15:23 UTC, xenkidu-va approved these changes
LGTM. Looks like a functioning, good starting point.

2021-07-06 21:28 UTC, as-va commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
Shouldn't need two changesets in one update.

2021-07-06 21:28 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/FacilityPair.java
> +  Facility v0;
In files that need to reference both versions, we should use fully qualified names for _both_ instead of importing one and qualifying the other.

2021-07-07 12:39 UTC, taylorrassmannlibertyits commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/FacilityPair.java
> +  Facility v0;
Ok, I was debating this. My train of thought was all v0 `Facility` objects didn't have the fully qualified name.

2021-07-07 12:40 UTC, taylorrassmannlibertyits commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
In the past when modifying different tables we've made two changeSets.

2021-07-07 14:06 UTC, as-va commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
I see that happened once in the initial vaccine service update, but it did not need to be that way. I think they got added at different times during that task and they were never coalesced back to a single change entry.

2021-07-07 15:36 UTC, taylorrassmannlibertyits commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
I'm still uneasy about changing this. I feel there was a reason to keep them separate before.

2021-07-08 18:40 UTC, as-va requested changes

2021-07-08 18:40 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
>    private static final ObjectMapper MAPPER = FacilitiesJacksonConfig.createMapper();
Anything that has to split out a V1 variant should change the original to `*V0`.

2021-07-08 18:40 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/ControllersV1.java
> +final class ControllersV1 {
In many places throughout the code new V1 classes have been created by cloning the existing files and appending "V1", but the old files are unchanged. Either both classes should keep a versionless name and be moved to a versioned package, or the existing implementations should be renamed to `*V0`.

2021-07-08 18:40 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
This makes the implicit assumption that both lists will be the same size and have the same elements in the same order. Only the last of those assumptions seems safe to make.

This should be the case in the _ideal_ situation, but I can see the possibility as v0 and v1 continue to diverge that some facility may meet one version's constraints but not the others causing a different set of Facilities collected and then this logic would break.

A safer approach if this is the way we want to handle collection would be to collect facilities as a map of `{id : obj}` for each version, iterate over the union of the set of ids from both, and extract facility objects from the maps based on id to ensure the pairs are initialized correctly.

2021-07-08 18:40 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalCollectorController.java
> +  List<FacilityPair> collectFacilities() {
This is changing the return type of an exposed endpoint. Are you sure we can make this change? It is an internal endpoint so no consumers can be using it, but could there be any other effects or implications of this change? Could Prometheus, pingdom, or any other monitoring tool be using this endpoint which would break with this change or are we certain it is only a back door for us?

2021-07-08 18:50 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
>    private static final ObjectMapper MAPPER = FacilitiesJacksonConfig.createMapper();
Ok, I did not do that originally to reduce the amount of files changed. I will make the update.

2021-07-08 18:51 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/ControllersV1.java
> +final class ControllersV1 {
Ok, I did not do that originally to reduce the amount of files changed. I will make the update.

2021-07-08 18:59 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/ControllersV1.java
> +final class ControllersV1 {
I agree it is a hassle, but without it gives the impression that (e.g.) `Facility` is the _real_ thing and `FacilityV1` is a variant or sub-type instead of them being parallel objects at the same level.

2021-07-08 19:12 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
I disagree. If we have a moment where there are `n` v0 facilities and `m` v1 facilities then something is _fundamentally_ wrong with the API.

Since these are two _sorted_ lists of v0 and v1 Facilities this _should_ be ok. 

I can add a check for if the different lists are not the same size and error out. 

I need more explanation on a scenario you think these two versions may diverge such that the pair option does not work.

2021-07-08 19:13 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalCollectorController.java
> +  List<FacilityPair> collectFacilities() {
Since this endpoint is _internal_ I think this change is ok. I will verify and update.

2021-07-08 19:41 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
Yes, there would be something critically wrong, but simply erroring out would put us in the same predicament we had several months ago where were were unable to reload or modify results in the API which seems a bad way to handle an error. It would be better to insert a null for the missing version string, or drop the unmatched object, or _anything_ that would let the API continue to operate with at least the known good data while we work to fix whatever the underlying error is.

2021-07-08 20:07 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
Ok I like that way of thinking. I'll work on a check if the id's match and throw a null into the v0 or v1 pair. I don't thinking dropping the facility would be ok

2021-07-08 21:12 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
null would be better if it works, but I just threw that out without looking back through the full stack. Would that cause a problem with serialization/deserialization later on trying to map the null to a FacilityVx object? I wasn't sure so I added the "drop the unmatched" option out as a backup.

2021-07-09 12:56 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
After looking into this more. I _still_ think this will not happen. The process using the **same** collection for v0 and v1, the transform is the only difference into different versions of facilities.

2021-07-12 14:39 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/ControllersV1.java
> +        throw new ExceptionsV0.InvalidParameter("services", service);
Do we need to break this out to have a `V1` version or can this be genericized to a common non-versioned `Exceptions` class?

2021-07-12 14:40 UTC, as-va commented
I know for a while you were keeping the documentation changes active so you could compare; since we are getting close to merging this, has that been deactivated? What will this merge do to the portal?

2021-07-12 14:46 UTC, as-va commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
To close this out, this part of the code change has been removed from this PR, but we should revisit this conversation before the follow up work to re-add.

2021-07-12 14:49 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/FacilitiesCollector.java
> +    for (int i = 0; i < facilities.size(); i++) {
Recapping an offline conversation: the collection is _currently_ the same, but this may change during the course of V1's lifetime. I think we should still have safe code for inserting into the db, but the db portion of this PR is being pushed back to allow the other pieces to merge so this can be revisited in a follow up task to re-add the db portion.

2021-07-12 15:35 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/ControllersV1.java
> +        throw new ExceptionsV0.InvalidParameter("services", service);
Probably can be made into an exceptions utils class

2021-07-12 15:36 UTC, taylorrassmannlibertyits commented
> I know for a while you were keeping the documentation changes active so you could compare; since we are getting close to merging this, has that been deactivated? What will this merge do to the portal?

The goal is to hide anything related to v1. This should be disabled in the upcoming push

2021-07-12 17:34 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalCollectorController.java
> +  List<FacilityPair> collectFacilities() {
I think we should be good here. I don't see anything else using this

2021-07-12 20:29 UTC, as-va approved these changes

2021-07-12 20:29 UTC, merged