Api 8854 v1 cms overlay updates
department-of-veterans-affairs/lighthouse-facilities pull request #232
Opened 2021-08-04 13:21 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-8954

Updated Facilities API to dynamically update a facility on receipt of CMS Overlay information in regards to upcoming v1 changes. Ripple effect throughout the code base.

2021-08-05 17:32 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/GeoFacilityTransformerV1.java
> +  //  @NonNull private final Facility facility;
is this code going to be used at a later time or can this be deleted?

2021-08-05 17:51 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/GeoFacilityTransformerV1.java
> +  //  @NonNull private final Facility facility;
Definitely going to be used later. This code should have been commented out from a previous PR since it is not currently in use.

2021-08-05 19:22 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayEntity.java
> +  @EqualsAndHashCode.Include @EmbeddedId private FacilityEntity.Pk id;
I think this should probably be a non-nullable field.

2021-08-05 19:23 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    Optional<FacilityEntity> existingFacilityEntity =
This method is kind of clunky & tough to follow, could we break it up into some more easily digestible parts?

2021-08-05 19:26 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    Optional<FacilityEntity> existingFacilityEntity =
Cool, I'll split it up into two separate methods for facility / cms overlay updates.

2021-08-05 19:29 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        facility.attributes().operatingStatus(overlay.operatingStatus());
We run the risk of overwriting existing non-null data with null data here.

2021-08-05 19:30 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        facility.attributes().operatingStatus(overlay.operatingStatus());
Good catch. We had this problem in the past. I'll make sure to make a test since I don't think one exists.

2021-08-06 15:17 UTC, as-va requested changes

2021-08-06 15:17 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (cmsOverlayRepository.findById(FacilityEntity.Pk.fromIdString(id)).isPresent()) {
You could find the entity once then check if it is present to avoid two lookup operations.

2021-08-06 15:17 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
This changes the existing behavior of the endpoint. I will verify with CMS if this will have any impact on their end.

2021-08-06 15:17 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
This is incorrect. Maybe there was a miscommunication in discussing this. CMS will always send the full payload for any service that has changed (meaning we do not need to persist any services that transition to inactive since we will get everything back if it is reenabled), but will _not_ send unchanged services. So this needs to:
* Add or replace any service that has `active: true`
* Delete any service that has `active: false`
* Keep all other stored services

2021-08-06 15:29 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
I think this code is correctly doing what you are suggesting. Could you present a case where this does not work?

My logic is:

- Get all active services from the overlay
- Only write those services to the respective `cmsServices` column
- If there was a change from active -> inactive for a service, it is no longer part of the active list so it will be "deleted"

2021-08-06 17:42 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
But this does not preserve any _existing_ services that were saved from previous calls.

If a Facility has services `A`, `B`, and `C` stored in the DB, then CMS turns off service 'B', we will get an overlay with service `B` with `active: false`. We need to remove that service, but keep `A` and `C` in the DB since they are still active.

2021-08-06 17:47 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
Does this mean the "full payload" is only for a changed service, and not the entire list of detailed services? If so, that was communicated to me incorrectly originally

2021-08-06 18:34 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
Yeah, that's what I assumed in the initial comment that something got lost in translation.

A payload in this context is what CMS sends us, which will not be the list of all services for a Facility, but individual service updates as individual services are updated.

2021-08-06 22:09 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        cmsOverlayEntity.cmsServices(
Behavior now updated

2021-08-09 12:48 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        for (DetailedService currentDetailedService : currentDetailedServices) {
This looks like it would be simpler if instead of breaking up the active updates across these loops, instead have the first loop only get unchanged services (in existing list but not in new list) and the second loop add all active items in new list.

2021-08-09 12:48 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +          if (!foundServiceToUpdate) {
This is incorrect. `foundServiceToUpdate` is only set to true if the incoming service is active. If the incoming service is _inactive_, it should not be persisted.

2021-08-09 12:48 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +          facility.attributes().detailedServices(activeServices.isEmpty() ? null : activeServices);
This will need the same updates as above to fix. Either break out the service update portion to a helper function both updates can call, or have the facility update pull from the already updated cms_overlay table instead of using the incoming overlay directly.

2021-08-09 12:56 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +        for (DetailedService currentDetailedService : currentDetailedServices) {
I will work on updating this way

2021-08-09 19:22 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
Just got feedback from CMS - they would like to keep the current behavior (`200` if overlay is applied to a facility, `201` if the facility is unknown).

2021-08-09 19:27 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
So this is not the best behavior, since we will be saving to the overlay table (with my current changes). A `200` response means request succeeded, but a `201` usually means success with a creation of a resource. In the old code no resource is created. We simply bail out. What do you suggest we do?

2021-08-09 19:46 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
Ah, I mistyped - the code sends a `202` (HTTP: Accepted) when the facility ID is unknown.

2021-08-09 19:49 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
Ok, so do you want to still save the overlay if there is an unknown facility?

2021-08-09 19:52 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
Yes, we store everything. If the stored overlay has a facility to apply to, return `200`; if the stored overlay does not (yet) have an associated facility, return `202`.

2021-08-09 19:53 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
This shouldn't change anything already done in this PR except update the HTTP response code so it behaves like it did before the change.

2021-08-09 19:54 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
Ok I will update behavior

2021-08-09 19:55 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    return ResponseEntity.ok().build();
There will be a ripple through some tests and some minor code changes.

2021-08-10 20:30 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (cmsOverlayRepository.findById(FacilityEntity.Pk.fromIdString(id)).isPresent()) {
Were you going to do this? This line has changed but it is still doing the lookup twice.

2021-08-11 19:02 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (cmsOverlayRepository.findById(FacilityEntity.Pk.fromIdString(id)).isPresent()) {
The isPresent is required since it returns an optional entity. A warning is thrown if you just try and keep the entity.

2021-08-12 17:12 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (cmsOverlayRepository.findById(FacilityEntity.Pk.fromIdString(id)).isPresent()) {
This `isPresent` is needed, yes, but two hits to the DB is not. I have fixed in the latest push.

2021-08-12 17:14 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +  void updateServiceUrlPaths(String id, List<DetailedService> detailedServices) {
This method was specifically named to replace covid 19 paths. I don't think this name should change

2021-08-12 17:22 UTC, as-va approved these changes
Approving as my initial change requests have been addressed, but as I was the last contributor to the branch, will wait for additional approvals before merging.

2021-08-12 17:25 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +  void updateServiceUrlPaths(String id, List<DetailedService> detailedServices) {
We only are actively supporting the vaccine service at this time, but any service we receive through this interface will need the path updated in the same way. This should be a generalized routine for all services, not one in particular.

2021-08-12 17:26 UTC, taylorrassmannlibertyits commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +  void updateServiceUrlPaths(String id, List<DetailedService> detailedServices) {
Based on this, then you need to rename the other information this method is handling and not just the name

2021-08-13 16:31 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (overlay.detailedServices() != null) {
getActiveServicesFromOverlay method could be used here, and resulting list added to finalDetailedServices.

2021-08-13 16:33 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +  CmsOverlayResponse getOverlay(@PathVariable("id") String id) {
this returns 200 OK when the overlay does not exist, 404 Not Found seems more appropriate.

2021-08-13 17:16 UTC, esubocz-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +                  cmsOverlayRepository.save(
when there has been no sms-overlay update, after this has been run, when I retrieve (for this test I used vha_523) the overlay, I get the response:
```
{
    "overlay": {}
}
```
there is no cms_overlay data for that Facility, but I would think that the ID should be populating from this, but it doesn't appear to be working properly.

2021-08-16 22:03 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +    if (overlay.detailedServices() != null) {
I did not reuse that function because that would have caused two cycles through the path updating and sort functions which would add an unnecessary `O(n)` and `O(n log n)` complexity.

2021-08-16 22:04 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayController.java
> +  CmsOverlayResponse getOverlay(@PathVariable("id") String id) {
Agreed. Changed this to properly set HTTP status codes and return `200` when a valid overlay is returned and `404` if no overlay exists.

2021-08-16 22:11 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +                  cmsOverlayRepository.save(
There is no ID in the response of a valid overlay _to_ populate, but this is still a good catch. `vha_523` is in the facility table, but `vha_000` is not. Neither ID has an overlay. Retrieving an overlay directly from the overlay table should have the same behavior if there is no overlay, but those two would have different results (the former returning an empty overlay and the latter returning a not found error). If there is no overlay, we should get back the `404` discussed above, not an empty overlay object. Updated this function to only migrate existing overlays from the facility table instead of creating empty overlays.

2021-08-17 17:16 UTC, esubocz-va approved these changes

2021-08-17 17:43 UTC, merged