Api 12146 json cleanup
department-of-veterans-affairs/lighthouse-facilities pull request #280
Opened 2022-01-20 21:02 UTC by JamesDanielBell-VA

https://vajira.max.gov/browse/API-12146
-moving v1 fields style to camelCase from snake_case
-this PR also contains API-12142

2022-01-20 22:22 UTC, mmccollum-va commented
The following files should be removed as a result of the efforts to deprecated `geo+json` in [API-12142](https://vajira.max.gov/browse/API-12142):

- `facilities`
    - `test/resources/v1/`
        - `read-benefits-geojson.json`
        - `read-cemetery-geojson.json`
        - `read-health-geojson.json`
        - `read-state-cemetery-geojson.json`
        - `read-vet-center-geojson.json`
        - `search-bbox-geojson.json`
        - `search-ids-geojson.json`
        - `search-lat-long-geojson.json`
        - `search-state-geojson.json`
        - `search-zip-geojson.json`

2022-01-20 22:38 UTC, JamesDanielBell-VA commented
thank you for the catch!
Will update PR

2022-01-21 17:45 UTC, mmccollum-va approved these changes

2022-01-21 17:52 UTC, JamesDanielBell-VA commented
Thanks for the catch on minTime and maxTime. The testerino was indeed for testing purposes. It was removed this morning following Adam's feedback in standup

2022-01-21 18:30 UTC, ChrisBratti-VA approved these changes

2022-01-21 19:02 UTC, mmccollum-va approved these changes

2022-01-24 15:28 UTC, giangnguyen2 approved these changes

2022-01-28 20:36 UTC, as-va commented on facilities-api/src/test/resources/v1/search-zip-geojson.json
> +        "facilityType" : "va_health_facility",
GeoJson is deprecated in V1 - this file should be removed.

2022-01-28 20:37 UTC, as-va commented on facilities-api/src/test/resources/v1/read-health-geojson.json
> +    "facilityType" : "va_health_facility",
GeoJson is deprecated in V1 - this file should be removed.

2022-01-28 20:39 UTC, as-va requested changes
Everything looks good except for the two GeoJson resource files in the V1 package. Remove those and we'll merge in the rest.

2022-01-31 16:39 UTC, as-va approved these changes

2022-01-31 16:40 UTC, merged