API-12145 F: V1: Add parent facility reference to Facilities records
department-of-veterans-affairs/lighthouse-facilities pull request #281
Opened 2022-01-21 21:47 UTC by giangnguyen2

Add parent reference to V1 facility Record
[API-12145](https://vajira.max.gov/browse/API-12145)

2022-01-21 22:56 UTC, mmccollum-va approved these changes

2022-01-25 16:27 UTC, ChrisBratti-VA commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/HealthTransformer.java
> +  private String parentId() {
Could simplify this to a one-liner with a ternary operator:
`return allBlank(vast.parentStationNumber()) ? null : "vha_" + vast.parentStationNumber();`

2022-01-25 16:27 UTC, ChrisBratti-VA commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/VetCenterTransformer.java
> +  private String parentId() {
Could simplify this to a one-liner with a ternary operator:
`return allBlank(vast.parentStationNumber()) ? null : "vc_" + vast.parentStationNumber();`

2022-01-25 17:48 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/HealthTransformer.java
> +  private String parentId() {
Good call! This has been addressed

2022-01-25 19:19 UTC, ChrisBratti-VA approved these changes

2022-01-31 12:44 UTC, mmccollum-va approved these changes

2022-01-31 18:21 UTC, as-va requested changes

2022-01-31 18:21 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v1/Facility.java
> -  @JsonPropertyOrder({
Why was this removed? This defines the ordering of fields in the API response.

2022-01-31 18:21 UTC, as-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +                "http://localhost:8085/v1/facilities/vha_123"));
These tests and resource files aren't just run on our local machines - they are also run on each of the AWS environments during application deployments. This hardcoded address will only work locally; it needs to run everywhere.

Take a look at `SystemDefinitions` in the facilities/test project for a helper class that can figure out where it is running and return the appropriate settings.

2022-01-31 19:55 UTC, giangnguyen2 commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v1/Facility.java
> -  @JsonPropertyOrder({
For V1, we now use a custom serializer `FacilityAttributesSerializer` which dictates the ordering of fields in the response so this ` @JsonPropertyOrde` code no longer have effect on the ordering of fields

2022-01-31 22:28 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +                "http://localhost:8085/v1/facilities/vha_123"));
Thanks for the reference. I have updated the code.

2022-02-02 14:29 UTC, mmccollum-va requested changes

2022-02-02 14:29 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .isInstanceOf(AssertionError.class);
Consider adding `.hasMessage(<error_msg_thrown>)` to include verification of the error message thrown in the test

2022-02-02 14:29 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
> -  })
No `@JsonSerializer` has been specified for `DatamartFacility.FacilityAttributes`. Consider reincluding `@JsonPropertyOrder`

2022-02-02 14:57 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
> -  })
I see that there is a custom `FacilityAttributesSerializer` in `DatamartJacksonSerializers`

2022-02-02 17:55 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .isInstanceOf(AssertionError.class);
I have added a message to this assert.

2022-02-02 19:01 UTC, mmccollum-va requested changes

2022-02-02 19:01 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
> -  })
True, `FacilityAttributesSerializer` in `DatamartJacksonSerializers` does ensure this property order, but it is possible to serialize `DatamartFacility` to JSON outside of `DatamartJacksonSerializers`. Setting `@JsonPropertyOrder` will ensure the expected order in such cases.

2022-02-02 19:48 UTC, mmccollum-va approved these changes

2022-02-02 20:12 UTC, mmccollum-va submitted a review, later dismissed

2022-02-03 14:38 UTC, ChrisBratti-VA approved these changes

2022-07-01 21:35 UTC, closed without merging