API-12978 consume new service id from cms overlay detailed service pa…
department-of-veterans-affairs/lighthouse-facilities pull request #284
Opened 2022-02-01 15:09 UTC by giangnguyen2

Consume new service id in cms overlay detailed service payload
Link to JIRA ticket [API-12978] (https://vajira.max.gov/browse/API-12978)

2022-02-01 20:28 UTC, as-va requested changes

2022-02-01 20:28 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/DetailedService.java
> +  String serviceId;
This needs a `@Schema` annotation as on the other fields here.

2022-02-01 20:28 UTC, as-va commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
Let's hold off on this change. I know we discussed possibly being able to coalesce this table and `facility_services`, but right now the code is still using both (see `FacilityEntity` which would break with this change). This isn't needed for this ticket so we can revisit cleaning this up in the future.

2022-02-02 20:59 UTC, giangnguyen2 commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/DetailedService.java
> +  String serviceId;
Update has been made to include @Schema annotation.

2022-02-03 01:54 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV0.java
> +        detailedServices.add(service.serviceId());
Consider refactoring this to be `detailedServices.add(StringUtils.capitalize(service.serviceId()));` This will enable the creation of `HealthService` values based off of the enum name (ie, capitalized `serviceId`)

2022-02-03 01:54 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1.java
> +        detailedServices.add(service.serviceId());
Consider refactoring this to be `detailedServices.add(StringUtils.capitalize(service.serviceId()));` This will enable the creation of `HealthService` values based off of the enum name (ie, capitalized `serviceId`)

2022-02-03 15:16 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV0.java
> +        detailedServices.add(service.serviceId());
Please disregard previous comment. This is being addressed in [API-12143](https://vajira.max.gov/browse/API-12143)

2022-02-03 15:16 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1.java
> +        detailedServices.add(service.serviceId());
Please disregard previous comment. This is being addressed in [API-12143](https://vajira.max.gov/browse/API-12143)

2022-02-03 21:22 UTC, giangnguyen2 commented on facilities/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
This change has been reverted

2022-02-04 01:55 UTC, mmccollum-va approved these changes

2022-02-07 22:08 UTC, as-va approved these changes

2022-02-07 22:09 UTC, merged