Api 13373 f v1 add search parameters to services endpoint
department-of-veterans-affairs/lighthouse-facilities pull request #301
Opened 2022-02-21 21:16 UTC by JamesDanielBell-VA

https://vajira.max.gov/browse/API-13373

-adding serviceIds and serviceType as parameters for /services endpoint.

2022-02-28 21:12 UTC, giangnguyen2 submitted a review, later dismissed

2022-09-07 20:41 UTC, mmccollum-va requested changes

2022-09-07 20:41 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +import java.util.*;
Consider configuring IntelliJ to avoid using * imports

2022-09-07 20:59 UTC, mmccollum-va commented
@JamesDanielBell-VA please look to resolve the identified merge conflicts

2022-09-13 19:02 UTC, ChrisBratti-VA approved these changes

2022-10-06 20:48 UTC, mmccollum-va requested changes

2022-10-06 20:48 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +import java.util.*;
Avoid using * imports. 
Replace with following:
```
 import java.util.Arrays;
 import java.util.HashSet;
 import java.util.List;
 import java.util.Optional;
 import java.util.Set;
```

2022-10-06 20:50 UTC, mmccollum-va commented
@JamesDanielBell-VA please resolve conflicting files listed below

2022-10-17 13:13 UTC, as-va commented
@mmccollum-va, ticket still has you listed as requesting changes but all of your comments have been closed. Can you confirm if you are still waiting on additional changes or if this is good to merge?

2022-10-17 15:47 UTC, merged