Adding health phone number to v0 and v1 with test coverage.
department-of-veterans-affairs/lighthouse-facilities pull request #332
Opened 2022-04-18 13:55 UTC by JamesDanielBell-VA

https://vajira.max.gov/browse/API-14990

Adding new health connect phone number to main phone block.
Adding test coverage for the new phone number.

2022-04-19 13:52 UTC, mmccollum-va approved these changes

2022-04-28 20:04 UTC, mmccollum-va submitted a review, later dismissed

2022-05-02 13:23 UTC, as-va requested changes

2022-05-02 14:53 UTC, JamesDanielBell-VA commented
Updated branch with addressed feedback

2022-05-02 19:01 UTC, as-va approved these changes

2022-05-02 19:03 UTC, merged