Api 14991 consume health connect cms
department-of-veterans-affairs/lighthouse-facilities pull request #339
Opened 2022-05-04 18:44 UTC by ChrisBratti-VA

2022-05-04 18:56 UTC, giangnguyen2 commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +        example = "Example Health Care System Name",
Is this a valid example?

2022-05-04 19:18 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +    } else if (thisNodeOnly.equalsIgnoreCase("system_information")) {
In the code block starting on line 216 when specific node is not specified, don't we need to delete `system information` as well?

2022-05-04 19:34 UTC, ChrisBratti-VA commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +    } else if (thisNodeOnly.equalsIgnoreCase("system_information")) {
Good catch, yeah we should be deleting the system_information node in that block as well, making the update now

2022-05-04 19:37 UTC, ChrisBratti-VA commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +        example = "Example Health Care System Name",
The example should probably be updated, but I'm not 100% what to put as an example as I don't know what the real system names look like

2022-05-06 13:43 UTC, as-va requested changes

2022-05-06 13:43 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +  public static final class SystemInformation {
I'm thinking we should change this to `HealthCareSystem`. Just "SystemInformation" is a little too generic and could lead someone not already familiar with the design to assume this structure contains things like ram, cpu, etc.

2022-05-06 13:43 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +  @Schema(description = "Contains information pertaining to a CMS system.", nullable = true)
A Health Care System is a construct of the VHA, not just the CMS. Consumers would not care that CMS is our source for this information. Also, as with above comment would be better to spell out the full HCS. Something like `Describes the Health Care System for a facility.`

2022-05-06 13:43 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v1/CmsOverlay.java
> +  public static final class SystemInformation {
See note on class name in V0 version of this file.

2022-05-06 13:43 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v1/CmsOverlay.java
> +  @Schema(description = "Contains information pertaining to a CMS system.", nullable = true)
See note on description in V0 version of this file.

2022-05-06 13:43 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayHelper.java
> +  /** Obtain DatamartFacility system informatoin from JSON string. */
_information_

2022-05-06 13:43 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayHelper.java
> +  /** Obtain JSON string representation of DatamartFacility system informatoion. */
_information_

2022-05-06 13:43 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV1.java
> +  public static gov.va.api.lighthouse.facilities.api.v1.CmsOverlay.SystemInformation
Shouldn't need the fully qualified path here.

edit: or in the lines below.

2022-05-06 13:43 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +    } else if (thisNodeOnly.equalsIgnoreCase("system_information")) {
This is an internal endpoint just for our use so we can have this work however we want - that said, I think this would be clearer to use the name of the node from the payload (i.e. `system`) rather than `system_information` here. In the case of the other nodes, the payload name and our internal name are the same. This is the first case where they differ, so we should define expectation here. My feeling is that deleting an overlay node should be reciprocal to creating the node, and `system` is the key that creates that portion of the overlay.

2022-05-06 13:43 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +  public static final class SystemInformation {
Make sure to also update other occurrences of the name in supporting classes such as Entities, Datamart, etc.

2022-05-06 20:30 UTC, as-va requested changes

2022-05-06 20:30 UTC, as-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/CmsOverlay.java
> +  CmsOverlay.HealthCareSystem healthCareSystem;
This class definition is in this file; should not need the `CmsOverlay.` qualifier.

2022-05-06 20:30 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/InternalFacilitiesController.java
> +    } else if (thisNodeOnly.equalsIgnoreCase("system")) {
In the next `if` block below this section, you need to add a null check against this new field. This section goes through each major node type and sequentially checks if they need to be deleted, setting the fields to null if so. Afterwards, we update the record: if _all_ the nodes have been wiped out, we delete the entire overlay, otherwise we save the modified overlay to persist the fields that remain while blanking the null ones. Currently, since `healthCareSystem` is not checked in that calculation, if the other fields have been blanked but a system node remains, the overlay will be deleted and erroneously delete this node as well.

2022-05-09 19:47 UTC, giangnguyen2 commented on facilities-tests/src/test/java/gov/va/api/lighthouse/facilities/tests/CmsOverlayIT.java
> +                .body(MAPPER.writeValueAsString(CmsOverlay.builder().healthCareSystem(sysInfo)))
Does this `CmsOverlay.builder().healthCareSystem(sysInfo)` work? I would think it needs `CmsOverlay.builder().healthCareSystem(sysInfo).build()`

2022-05-09 20:07 UTC, ChrisBratti-VA commented on facilities-tests/src/test/java/gov/va/api/lighthouse/facilities/tests/CmsOverlayIT.java
> +                .body(MAPPER.writeValueAsString(CmsOverlay.builder().healthCareSystem(sysInfo)))
It actually does seem to work, I guess the mapper also supports the CmsBuilder object and serializes it to a String correctly. However I think it would be best practice to add the `.build()` on, making the update now

2022-05-09 20:28 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayEntity.java
> +  private Set<String> overlayServices = new HashSet<>();
I think we should remove this attribute, This change is for API-14307 and it needs other changes in API-14307. It most likely will cause bad side effect during reload without other changes.

2022-05-09 20:43 UTC, as-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayEntity.java
> +  private Set<String> overlayServices = new HashSet<>();
Agreed. I have not noticed any side effects in testing, but this does not need to be here and should stay in 14307 with the rest of this feature.

2022-05-09 20:53 UTC, ChrisBratti-VA commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayEntity.java
> +  private Set<String> overlayServices = new HashSet<>();
I'm in agreeance as well, I didn't see any issues with removing it but wanted to get other opinions before removing it completely. Making that update now

2022-05-09 22:03 UTC, as-va approved these changes

2022-05-09 22:04 UTC, merged