Api 13371 v1 remove active status
department-of-veterans-affairs/lighthouse-facilities pull request #354
Opened 2022-06-15 13:57 UTC by JamesDanielBell-VA

https://vajira.max.gov/browse/API-13371

- Removing activeStatus from V1

- Updating unit tests

2022-06-15 18:45 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1.java
> +  private static OperatingStatus determineOperatingStatusFromActiveStatus(
This function maybe conflicting or no longer need after [API-15738](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/348)

2022-08-18 13:23 UTC, as-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV0Test.java
> +        .ignoringFields("attributes.detailedServices")
Ignoring `detailedServices` twice?

2022-08-18 13:23 UTC, as-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV0Test.java
> +        .ignoringFields("attributes.detailedServices")
Additional fields don't need a new `ignoringFields` method - they can be added to the list in the existing one.

2022-08-18 13:23 UTC, as-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .ignoringFields("attributes.detailedServices")
These can all be combined into a single method call.

2022-08-18 13:23 UTC, as-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .ignoringFields("attributes.detailedServices")
See above.

2022-08-18 14:13 UTC, JamesDanielBell-VA commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .ignoringFields("attributes.detailedServices")
Updated!

2022-08-18 14:13 UTC, JamesDanielBell-VA commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV1Test.java
> +        .ignoringFields("attributes.detailedServices")
Updated!

2022-08-18 14:13 UTC, JamesDanielBell-VA commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/FacilityTransformerV0Test.java
> +        .ignoringFields("attributes.detailedServices")
Updated!

2022-08-18 14:16 UTC, as-va approved these changes

2022-09-07 20:55 UTC, mmccollum-va commented
@JamesDanielBell-VA please look to resolve the above merge conflicts

2022-09-14 13:25 UTC, ChrisBratti-VA approved these changes

2022-10-06 20:55 UTC, mmccollum-va approved these changes

2022-10-07 11:55 UTC, as-va requested changes
Please remove the `.DS_Store` file, then PR will be ready to merge.

2022-10-12 10:33 UTC, as-va approved these changes

2022-10-12 10:40 UTC, as-va requested changes
The merge of the base branch into this one added a new v1/CmsOverlayIT file which has references to ActiveStatus. That new file need to be updated to be compatible with the changes introduced in this PR; this branch is broken until then.

2022-10-13 11:06 UTC, as-va approved these changes

2022-10-13 11:07 UTC, merged