Api 10478 f v1 create service item endpoint
department-of-veterans-affairs/lighthouse-facilities pull request #357
Opened 2022-06-27 20:02 UTC by ChrisBratti-VA

2022-12-01 15:40 UTC, mmccollum-va requested changes

2022-12-01 15:40 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/BaseCmsOverlayController.java
> +    if (!isValidService(serviceId)) {
Redundant valid service check for serviceId. Please remove

2022-12-02 14:41 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/BaseCmsOverlayController.java
> +    if (!isValidService(serviceId)) {
@JamesDanielBell-VA please have as look at removing this redundant check

2022-12-05 16:15 UTC, mmccollum-va submitted a review, later dismissed

2023-04-12 20:45 UTC, as-va approved these changes

2023-04-14 11:38 UTC, merged