API-17020 F: Implement logic to handle facility URL push from CMS
department-of-veterans-affairs/lighthouse-facilities pull request #359
Opened 2022-06-29 16:44 UTC by giangnguyen2

Implement logic to handle facility url push from cms to save it to database

2022-07-07 10:52 UTC, mmccollum-va requested changes
Challenge to see `API-17020` specific changes with `API-12977` changes (not yet merged to `master`) interspersed throughout

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV0.java
> +  public static CmsOverlay.Core transformToCore(DatamartCmsOverlay.Core core) {
Consider renaming method to `toCore`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV0.java
> +  public static DatamartCmsOverlay.Core transformToVersionAgnosticCore(CmsOverlay.Core core) {
Consider renaming method to `toVersionAgnosticCore`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV1.java
> +  public static CmsOverlay.Core transformToCore(DatamartCmsOverlay.Core core) {
Consider renaming method to `toCore`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV1.java
> +  public static DatamartCmsOverlay.Core transformToVersionAgnosticCore(CmsOverlay.Core core) {
Consider renaming method to `toVersionAgnosticCore`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/CmsOverlayCollector.java
> +            });
Consider adding the following filters prior to `forEach`:
```
    datamartFacilities.stream()
        .filter(df -> overlayEntityMap.containsKey(df.id()))
        .filter(df -> df.attributes().waitTimes() != null)
        .filter(df -> df.attributes().waitTimes().health() != null)
        .forEach(
            datamartFacility -> {
                WaitTimes atcWaitTimes = datamartFacility.attributes().waitTimes();
                  List<PatientWaitTime> patientWaitTimes = atcWaitTimes.health();
                  LocalDate effectiveDate = atcWaitTimes.effectiveDate();
                  Map<String, PatientWaitTime> waitTimeMap =
                      patientWaitTimes.stream()
                          .collect(
                              Collectors.toMap(
                                  s -> uncapitalize(s.service().name()), Function.identity()));
                  CmsOverlayEntity cmsOverlayEntity = overlayEntityMap.get(datamartFacility.id());
                  List<DatamartDetailedService> cmsDatamartDetailedServices =
                      Optional.ofNullable(
                              CmsOverlayHelper.getDetailedServices(cmsOverlayEntity.cmsServices()))
                          .orElse(List.of());
                  cmsDatamartDetailedServices.stream()
                      .forEach(
                          cmsService -> {
                            String serviceId = cmsService.serviceInfo().serviceId();
                            PatientWaitTime patientWaitTime = waitTimeMap.get(serviceId);
                            if (patientWaitTime != null) {
                              cmsService.waitTime(
                                  DatamartDetailedService.PatientWaitTime.builder()
                                      .newPatientWaitTime(patientWaitTime.newPatientWaitTime())
                                      .establishedPatientWaitTime(
                                          patientWaitTime.establishedPatientWaitTime())
                                      .effectiveDate(effectiveDate)
                                      .build());
                            }
                          });
                  cmsOverlayEntity.cmsServices(
                      CmsOverlayHelper.serializeDetailedServices(cmsDatamartDetailedServices));
            });
```

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV0Test.java
> +        .forEach(
Consider filtering on Cardiology `serviceId` prior to `forEach`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +        .ignoringFields("core")
Curious why ignoring `core` field in this assertion

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +        .forEach(
Consider filtering on Cardiology `serviceId` prior to `forEach`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +        .filter(ds -> !ds.serviceInfo().serviceId.equals(HealthService.Covid19Vaccine.name()))
`serviceId` for equality comparison:
`ds -> !ds.serviceInfo().serviceId().equals(HealthService.Covid19Vaccine.serviceId())`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +              if (ds.serviceInfo().serviceId().equals(HealthService.Cardiology.name())) {
`serviceId` for equality comparison:
`ds.serviceInfo().serviceId().equals(HealthService.Cardiology.serviceId())`

2022-07-07 10:52 UTC, mmccollum-va commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +              if (ds.serviceInfo().serviceId().equals(HealthService.Urology.name())) {
`serviceId` for equality comparison:
`ds.serviceInfo().serviceId().equals(HealthService.Urology.serviceId())`

2022-07-07 10:53 UTC, mmccollum-va commented
Re-review once `API-12977` merged to `master`

2022-07-07 21:12 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +        .ignoringFields("core")
This is because the `controller().getOverlay()` is designed to not show `core` attribute in `CmsOverlayResponse`(Consumer won't see this field in response they receive). The `overlay` object in test is created with `core` attribute in it  so we want to to ignore it in this test. We use a common `overlay` objects for all test in this file.

2022-07-08 13:41 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV0Test.java
> +        .forEach(
Filter is not using here because I wan to keep all services and only update Cardiology active status to `false`. This way, the test case has a mixture of active services and in active services so that I can make sure that inactive service being removed correctly.

2022-07-08 17:19 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +        .forEach(
Filter is not using here because I wan to keep all services and only update Cardiology active status to false. This way, the test case has a mixture of active services and in active services so that I can make sure that inactive service being removed correctly.

2022-07-08 21:31 UTC, as-va commented
> Re-review once `API-12977` merged to `master`

API-12977 has been merged.

2022-07-11 16:22 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV0.java
> +  public static CmsOverlay.Core transformToCore(DatamartCmsOverlay.Core core) {
Done

2022-07-11 16:22 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/CmsOverlayTransformerV0.java
> +  public static DatamartCmsOverlay.Core transformToVersionAgnosticCore(CmsOverlay.Core core) {
Done

2022-07-11 16:23 UTC, giangnguyen2 commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/collector/CmsOverlayCollector.java
> +            });
This is on wait times stuff. I will look at this in API-17336

2022-07-11 16:23 UTC, giangnguyen2 commented on facilities/src/test/java/gov/va/api/lighthouse/facilities/CmsOverlayControllerV1Test.java
> +              if (ds.serviceInfo().serviceId().equals(HealthService.Cardiology.name())) {
Done

2022-07-11 16:24 UTC, giangnguyen2 commented
All feedback has been addressed

2022-07-11 22:12 UTC, mmccollum-va approved these changes

2022-09-07 20:57 UTC, mmccollum-va commented
@JamesDanielBell-VA please look to resolve the identified merge conflicts

2022-09-13 20:01 UTC, ChrisBratti-VA approved these changes

2022-10-06 20:37 UTC, mmccollum-va requested changes

2022-10-06 20:37 UTC, mmccollum-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v1/CmsOverlay.java
> +        && ObjectUtils.isEmpty(detailedServices());
If appears that check for `healthCareSystem` emptiness was mistakenly dropped. Consider
```
(core() == null || core().isEmpty())
   && (operatingStatus() == null || operatingStatus().isEmpty())
   && ObjectUtils.isEmpty(detailedServices())
   && (healthCareSystem() == null || healthCareSystem().isEmpty());
```

2022-10-20 15:49 UTC, merged