API-20452 - F: Spike: Investigate improvements of api level processing for the /nearby endpoint
department-of-veterans-affairs/lighthouse-facilities pull request #399
Opened 2022-10-11 16:50 UTC by mmccollum-va

- Parallel Stream Optimization - use `findAny()`, rather than `findFirst()`, when using parallel search based on `serviceId`. `serviceId` guaranteed to be unique across all services. `findFirst` causes parallel to continue search to the left to ensure match is first after match is found.

2022-10-25 16:10 UTC, bschofield-va requested changes
Preventing merge into master

2022-10-25 16:19 UTC, bschofield-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/pssg/PathEncoderTest.java
> +    if (path.isPresent()) {
From a test perspective... aren't we in control of whether we expect the `path` to be present or not? I'm not sure I understand why this test may not perform any assertions at all.

2022-10-25 16:24 UTC, bschofield-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/pssg/PathEncoder.java
> +    if (buffer.hasRemaining()) {
I get that is method is handling for the buffer underflow condition that can arise from invalid path data. _How does that path data become corrupted to begin with?_ I can certainly be wrong, but this feels like this is compensating for a symptom of a problem rather than fixing the root problem itself.

2022-10-25 16:25 UTC, bschofield-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/Facility.java
> +          .findAny();
out of curiosity, does `findAny` give us better performance than `findFirst`?

2022-10-25 18:04 UTC, mmccollum-va commented on facilities-api/src/main/java/gov/va/api/lighthouse/facilities/api/v0/Facility.java
> +          .findAny();
In theory, yes. Intent is to quickly find services based on their unique identifier. Both `findAny` and `findFirst` can achieve this using parallel streams, however, `findFirst` must take additional steps to ensure match is first in collection. `findAny` used here to avoid the extra steps.

2022-10-25 18:07 UTC, mmccollum-va commented on facilities-api/src/test/java/gov/va/api/lighthouse/facilities/api/pssg/PathEncoderTest.java
> +    if (path.isPresent()) {
This change was made to account for DTBs with no geometries

2023-01-09 19:05 UTC, mmccollum-va commented
- GitHub [PR](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/399) has been open for **`2.5` months**
    - It has been recommended to close this [PR](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/399) and re-open it if it becomes useful and/or needed in the future

2023-01-09 19:05 UTC, closed without merging