Api 26694 datamart ignoreproperties
department-of-veterans-affairs/lighthouse-facilities pull request #452
Opened 2023-05-18 16:25 UTC by ChrisBratti-VA

2023-05-18 17:47 UTC, mmccollum-va requested changes

2023-05-18 17:47 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartDetailedService.java
>      @JsonAlias({"service_id", "service_api_id"})
Consider adding `@JsonIgnoreProperties(ignoreUnknown = true)` to `ServiceInfoBuilder` inner class

2023-05-18 17:47 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
Consider  adding `@JsonIgnoreProperties(ignoreUnknown = true)` to `HoursBuilder` inner class

2023-05-18 17:47 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
>      "facility_type",
Consider adding `@JsonIgnoreProperties(ignoreUnknown = true)` to `FacilitiesAttributesBuilder` inner class

2023-05-18 17:47 UTC, mmccollum-va commented on facilities/src/main/java/gov/va/api/lighthouse/facilities/DatamartFacility.java
>    public static final class Service<T extends TypedService> implements Comparable<Service<T>> {
Consider adding `@JsonIgnoreProperties(ignoreUnknown = true)` to `ServiceBuilder` inner class

2023-05-19 20:38 UTC, as-va requested changes
Can you add into the DeserializerTest a verification that receiving an unknown field is properly ignored and still results in a valid object build from the test data?

2023-05-23 20:13 UTC, as-va approved these changes

2023-05-23 20:14 UTC, merged